/*
 * @author Mário Soares
 * @contributors Jefferson González
 * @contributors René Vögeli / Rangee GmbH
 * 
 * @license 
 * This file is part of wxPHP check the LICENSE file for information.
 * 
 * @note
 * This file was auto-generated by the wxPHP source maker
*/

#ifndef WXPHP_HTML_H_GUARD
#define WXPHP_HTML_H_GUARD

#include "references.h"
#include "object_types.h"

ZEND_BEGIN_ARG_INFO_EX(wxphp_html_get_args, 0, 0, 1)
    ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

extern zend_class_entry* php_wxHtmlHelpController_entry;
extern zend_object_handlers wxphp_wxHtmlHelpController_object_handlers;
void php_wxHtmlHelpController_destruction_handler(zend_resource*);

class wxHtmlHelpController_php: public wxHtmlHelpController{
    public:

    wxHtmlHelpController_php(int style=wxHF_DEFAULT_STYLE, wxWindow* parentWindow=NULL):wxHtmlHelpController(style, parentWindow){}
    wxHtmlHelpController_php(wxWindow* parentWindow, int style=wxHF_DEFAULT_STYLE):wxHtmlHelpController(parentWindow, style){}
    
    wxHtmlHelpDialog* CreateHelpDialog(wxHtmlHelpData* data);
    wxHtmlHelpFrame* CreateHelpFrame(wxHtmlHelpData* data);
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlHelpController{
    wxHtmlHelpController_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlHelpController;

void php_wxHtmlHelpController_free(zend_object *object);
zend_object* php_wxHtmlHelpController_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlHelpController_functions[] = {
    PHP_ME(php_wxHtmlHelpController, AddBook, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, Display, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, DisplayContents, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, DisplayIndex, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, KeywordSearch, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, ReadCustomization, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, SetShouldPreventAppExit, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, SetTempDir, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, SetTitleFormat, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, UseConfig, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, WriteCustomization, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpController, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlHelpController * php_wxHtmlHelpController_fetch_object(zend_object *obj) {
    return (zo_wxHtmlHelpController *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlHelpController, zo)
    );
}

#define Z_wxHtmlHelpController_P(zv) \
    php_wxHtmlHelpController_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlModalHelp_entry;
extern zend_object_handlers wxphp_wxHtmlModalHelp_object_handlers;
void php_wxHtmlModalHelp_destruction_handler(zend_resource*);

class wxHtmlModalHelp_php: public wxHtmlModalHelp{
    public:

    wxHtmlModalHelp_php(wxWindow* parent, const wxString& helpFile, const wxString& topic=wxEmptyString, int style=wxHF_DEFAULT_STYLE|wxHF_DIALOG|wxHF_MODAL):wxHtmlModalHelp(parent, helpFile, topic, style){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlModalHelp{
    wxHtmlModalHelp_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlModalHelp;

void php_wxHtmlModalHelp_free(zend_object *object);
zend_object* php_wxHtmlModalHelp_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlModalHelp_functions[] = {
    PHP_ME(php_wxHtmlModalHelp, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlModalHelp * php_wxHtmlModalHelp_fetch_object(zend_object *obj) {
    return (zo_wxHtmlModalHelp *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlModalHelp, zo)
    );
}

#define Z_wxHtmlModalHelp_P(zv) \
    php_wxHtmlModalHelp_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlHelpData_entry;
extern zend_object_handlers wxphp_wxHtmlHelpData_object_handlers;
void php_wxHtmlHelpData_destruction_handler(zend_resource*);

class wxHtmlHelpData_php: public wxHtmlHelpData{
    public:

    wxHtmlHelpData_php():wxHtmlHelpData(){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlHelpData{
    wxHtmlHelpData_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlHelpData;

void php_wxHtmlHelpData_free(zend_object *object);
zend_object* php_wxHtmlHelpData_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlHelpData_functions[] = {
    PHP_ME(php_wxHtmlHelpData, AddBook, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpData, FindPageById, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpData, FindPageByName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpData, SetTempDir, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpData, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlHelpData * php_wxHtmlHelpData_fetch_object(zend_object *obj) {
    return (zo_wxHtmlHelpData *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlHelpData, zo)
    );
}

#define Z_wxHtmlHelpData_P(zv) \
    php_wxHtmlHelpData_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlHelpDialog_entry;
extern zend_object_handlers wxphp_wxHtmlHelpDialog_object_handlers;
void php_wxHtmlHelpDialog_destruction_handler(zend_resource*);

class wxHtmlHelpDialog_php: public wxHtmlHelpDialog{
    public:

    wxHtmlHelpDialog_php(wxHtmlHelpData* data=NULL):wxHtmlHelpDialog(data){}
    wxHtmlHelpDialog_php(wxWindow* parent, wxWindowID id, const wxString& title=wxEmptyString, int style=wxHF_DEFAULT_STYLE, wxHtmlHelpData* data=NULL):wxHtmlHelpDialog(parent, id, title, style, data){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlHelpDialog{
    wxHtmlHelpDialog_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlHelpDialog;

void php_wxHtmlHelpDialog_free(zend_object *object);
zend_object* php_wxHtmlHelpDialog_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlHelpDialog_functions[] = {
    PHP_ME(php_wxHtmlHelpDialog, AddToolbarButtons, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpDialog, Create, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpDialog, GetController, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpDialog, SetController, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpDialog, SetTitleFormat, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpDialog, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlHelpDialog * php_wxHtmlHelpDialog_fetch_object(zend_object *obj) {
    return (zo_wxHtmlHelpDialog *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlHelpDialog, zo)
    );
}

#define Z_wxHtmlHelpDialog_P(zv) \
    php_wxHtmlHelpDialog_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlHelpFrame_entry;
extern zend_object_handlers wxphp_wxHtmlHelpFrame_object_handlers;
void php_wxHtmlHelpFrame_destruction_handler(zend_resource*);

class wxHtmlHelpFrame_php: public wxHtmlHelpFrame{
    public:

    wxHtmlHelpFrame_php(wxHtmlHelpData* data=NULL):wxHtmlHelpFrame(data){}
    wxHtmlHelpFrame_php(wxWindow* parent, wxWindowID id, const wxString& title=wxEmptyString, int style=wxHF_DEFAULT_STYLE, wxHtmlHelpData* data=NULL, wxConfigBase* config=NULL, const wxString& rootpath=wxEmptyString):wxHtmlHelpFrame(parent, id, title, style, data, config, rootpath){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlHelpFrame{
    wxHtmlHelpFrame_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlHelpFrame;

void php_wxHtmlHelpFrame_free(zend_object *object);
zend_object* php_wxHtmlHelpFrame_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlHelpFrame_functions[] = {
    PHP_ME(php_wxHtmlHelpFrame, AddToolbarButtons, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpFrame, Create, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpFrame, GetController, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpFrame, SetController, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpFrame, SetTitleFormat, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpFrame, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlHelpFrame * php_wxHtmlHelpFrame_fetch_object(zend_object *obj) {
    return (zo_wxHtmlHelpFrame *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlHelpFrame, zo)
    );
}

#define Z_wxHtmlHelpFrame_P(zv) \
    php_wxHtmlHelpFrame_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlHelpWindow_entry;
extern zend_object_handlers wxphp_wxHtmlHelpWindow_object_handlers;
void php_wxHtmlHelpWindow_destruction_handler(zend_resource*);

class wxHtmlHelpWindow_php: public wxHtmlHelpWindow{
    public:

    wxHtmlHelpWindow_php(wxHtmlHelpData* data=NULL):wxHtmlHelpWindow(data){}
    wxHtmlHelpWindow_php(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, int style=wxTAB_TRAVERSAL|wxBORDER_NONE, int helpStyle=wxHF_DEFAULT_STYLE, wxHtmlHelpData* data=NULL):wxHtmlHelpWindow(parent, id, pos, size, style, helpStyle, data){}
    
    void AddToolbarButtons(wxToolBar* toolBar, int style);
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlHelpWindow{
    wxHtmlHelpWindow_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlHelpWindow;

void php_wxHtmlHelpWindow_free(zend_object *object);
zend_object* php_wxHtmlHelpWindow_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlHelpWindow_functions[] = {
    PHP_ME(php_wxHtmlHelpWindow, Create, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, Display, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, DisplayIndex, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, GetData, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, DisplayContents, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, KeywordSearch, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, ReadCustomization, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, RefreshLists, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, UseConfig, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, WriteCustomization, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlHelpWindow, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlHelpWindow * php_wxHtmlHelpWindow_fetch_object(zend_object *obj) {
    return (zo_wxHtmlHelpWindow *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlHelpWindow, zo)
    );
}

#define Z_wxHtmlHelpWindow_P(zv) \
    php_wxHtmlHelpWindow_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlRenderingStyle_entry;
extern zend_object_handlers wxphp_wxHtmlRenderingStyle_object_handlers;
void php_wxHtmlRenderingStyle_destruction_handler(zend_resource*);

class wxHtmlRenderingStyle_php: public wxHtmlRenderingStyle{
    public:

    
    wxColour GetSelectedTextBgColour(const wxColour& clr);
    wxColour GetSelectedTextColour(const wxColour& clr);
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlRenderingStyle{
    wxHtmlRenderingStyle_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlRenderingStyle;

void php_wxHtmlRenderingStyle_free(zend_object *object);
zend_object* php_wxHtmlRenderingStyle_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlRenderingStyle_functions[] = {
    PHP_FE_END
};
#endif


static inline zo_wxHtmlRenderingStyle * php_wxHtmlRenderingStyle_fetch_object(zend_object *obj) {
    return (zo_wxHtmlRenderingStyle *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlRenderingStyle, zo)
    );
}

#define Z_wxHtmlRenderingStyle_P(zv) \
    php_wxHtmlRenderingStyle_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlRenderingInfo_entry;
extern zend_object_handlers wxphp_wxHtmlRenderingInfo_object_handlers;
void php_wxHtmlRenderingInfo_destruction_handler(zend_resource*);

class wxHtmlRenderingInfo_php: public wxHtmlRenderingInfo{
    public:

    wxHtmlRenderingInfo_php():wxHtmlRenderingInfo(){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlRenderingInfo{
    wxHtmlRenderingInfo_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlRenderingInfo;

void php_wxHtmlRenderingInfo_free(zend_object *object);
zend_object* php_wxHtmlRenderingInfo_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlRenderingInfo_functions[] = {
    PHP_ME(php_wxHtmlRenderingInfo, GetStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlRenderingInfo, SetStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlRenderingInfo, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlRenderingInfo * php_wxHtmlRenderingInfo_fetch_object(zend_object *obj) {
    return (zo_wxHtmlRenderingInfo *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlRenderingInfo, zo)
    );
}

#define Z_wxHtmlRenderingInfo_P(zv) \
    php_wxHtmlRenderingInfo_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlCell_entry;
extern zend_object_handlers wxphp_wxHtmlCell_object_handlers;
void php_wxHtmlCell_destruction_handler(zend_resource*);

class wxHtmlCell_php: public wxHtmlCell{
    public:

    wxHtmlCell_php():wxHtmlCell(){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlCell{
    wxHtmlCell_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlCell;

void php_wxHtmlCell_free(zend_object *object);
zend_object* php_wxHtmlCell_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlCell_functions[] = {
    PHP_ME(php_wxHtmlCell, GetDescent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetFirstChild, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetHeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetId, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetLink, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetNext, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetPosX, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetPosY, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, GetWidth, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, Layout, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, SetId, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, SetLink, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, SetNext, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, SetParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, SetPos, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlCell, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxHtmlCell, Find, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlCell * php_wxHtmlCell_fetch_object(zend_object *obj) {
    return (zo_wxHtmlCell *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlCell, zo)
    );
}

#define Z_wxHtmlCell_P(zv) \
    php_wxHtmlCell_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlContainerCell_entry;
extern zend_object_handlers wxphp_wxHtmlContainerCell_object_handlers;
void php_wxHtmlContainerCell_destruction_handler(zend_resource*);

class wxHtmlContainerCell_php: public wxHtmlContainerCell{
    public:

    wxHtmlContainerCell_php(wxHtmlContainerCell* parent):wxHtmlContainerCell(parent){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlContainerCell{
    wxHtmlContainerCell_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlContainerCell;

void php_wxHtmlContainerCell_free(zend_object *object);
zend_object* php_wxHtmlContainerCell_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlContainerCell_functions[] = {
    PHP_ME(php_wxHtmlContainerCell, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxHtmlContainerCell, SetWidthFloat, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, SetMinHeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, SetIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, SetBorder, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, SetBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, SetAlignVer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, SetAlignHor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, SetAlign, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, InsertCell, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, GetIndentUnits, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, GetIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, GetBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, GetAlignVer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlContainerCell, GetAlignHor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlContainerCell * php_wxHtmlContainerCell_fetch_object(zend_object *obj) {
    return (zo_wxHtmlContainerCell *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlContainerCell, zo)
    );
}

#define Z_wxHtmlContainerCell_P(zv) \
    php_wxHtmlContainerCell_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlLinkInfo_entry;
extern zend_object_handlers wxphp_wxHtmlLinkInfo_object_handlers;
void php_wxHtmlLinkInfo_destruction_handler(zend_resource*);

class wxHtmlLinkInfo_php: public wxHtmlLinkInfo{
    public:

    wxHtmlLinkInfo_php():wxHtmlLinkInfo(){}
    wxHtmlLinkInfo_php(const wxString& href, const wxString& target=wxEmptyString):wxHtmlLinkInfo(href, target){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlLinkInfo{
    wxHtmlLinkInfo_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlLinkInfo;

void php_wxHtmlLinkInfo_free(zend_object *object);
zend_object* php_wxHtmlLinkInfo_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlLinkInfo_functions[] = {
    PHP_ME(php_wxHtmlLinkInfo, GetEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlLinkInfo, GetHref, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlLinkInfo, GetHtmlCell, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlLinkInfo, GetTarget, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlLinkInfo, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlLinkInfo * php_wxHtmlLinkInfo_fetch_object(zend_object *obj) {
    return (zo_wxHtmlLinkInfo *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlLinkInfo, zo)
    );
}

#define Z_wxHtmlLinkInfo_P(zv) \
    php_wxHtmlLinkInfo_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlColourCell_entry;
extern zend_object_handlers wxphp_wxHtmlColourCell_object_handlers;
void php_wxHtmlColourCell_destruction_handler(zend_resource*);

class wxHtmlColourCell_php: public wxHtmlColourCell{
    public:

    wxHtmlColourCell_php(const wxColour& clr, int flags=wxHTML_CLR_FOREGROUND):wxHtmlColourCell(clr, flags){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlColourCell{
    wxHtmlColourCell_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlColourCell;

void php_wxHtmlColourCell_free(zend_object *object);
zend_object* php_wxHtmlColourCell_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlColourCell_functions[] = {
    PHP_ME(php_wxHtmlColourCell, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlColourCell * php_wxHtmlColourCell_fetch_object(zend_object *obj) {
    return (zo_wxHtmlColourCell *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlColourCell, zo)
    );
}

#define Z_wxHtmlColourCell_P(zv) \
    php_wxHtmlColourCell_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlWidgetCell_entry;
extern zend_object_handlers wxphp_wxHtmlWidgetCell_object_handlers;
void php_wxHtmlWidgetCell_destruction_handler(zend_resource*);

class wxHtmlWidgetCell_php: public wxHtmlWidgetCell{
    public:

    wxHtmlWidgetCell_php(wxWindow* wnd, int w=0):wxHtmlWidgetCell(wnd, w){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlWidgetCell{
    wxHtmlWidgetCell_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlWidgetCell;

void php_wxHtmlWidgetCell_free(zend_object *object);
zend_object* php_wxHtmlWidgetCell_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlWidgetCell_functions[] = {
    PHP_ME(php_wxHtmlWidgetCell, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlWidgetCell * php_wxHtmlWidgetCell_fetch_object(zend_object *obj) {
    return (zo_wxHtmlWidgetCell *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlWidgetCell, zo)
    );
}

#define Z_wxHtmlWidgetCell_P(zv) \
    php_wxHtmlWidgetCell_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlFilter_entry;
extern zend_object_handlers wxphp_wxHtmlFilter_object_handlers;
void php_wxHtmlFilter_destruction_handler(zend_resource*);

class wxHtmlFilter_php: public wxHtmlFilter{
    public:

    wxHtmlFilter_php():wxHtmlFilter(){}
    
    bool CanRead(const wxFSFile& file) const;
    wxString ReadFile(const wxFSFile& file) const;
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlFilter{
    wxHtmlFilter_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlFilter;

void php_wxHtmlFilter_free(zend_object *object);
zend_object* php_wxHtmlFilter_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlFilter_functions[] = {
    PHP_ME(php_wxHtmlFilter, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlFilter * php_wxHtmlFilter_fetch_object(zend_object *obj) {
    return (zo_wxHtmlFilter *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlFilter, zo)
    );
}

#define Z_wxHtmlFilter_P(zv) \
    php_wxHtmlFilter_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlTagHandler_entry;
extern zend_object_handlers wxphp_wxHtmlTagHandler_object_handlers;
void php_wxHtmlTagHandler_destruction_handler(zend_resource*);

class wxHtmlTagHandler_php: public wxHtmlTagHandler{
    public:

    wxHtmlTagHandler_php():wxHtmlTagHandler(){}
    
    wxString GetSupportedTags();
    bool HandleTag(const wxHtmlTag& tag);
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlTagHandler{
    wxHtmlTagHandler_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlTagHandler;

void php_wxHtmlTagHandler_free(zend_object *object);
zend_object* php_wxHtmlTagHandler_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlTagHandler_functions[] = {
    PHP_ME(php_wxHtmlTagHandler, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlTagHandler * php_wxHtmlTagHandler_fetch_object(zend_object *obj) {
    return (zo_wxHtmlTagHandler *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlTagHandler, zo)
    );
}

#define Z_wxHtmlTagHandler_P(zv) \
    php_wxHtmlTagHandler_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlTag_entry;
extern zend_object_handlers wxphp_wxHtmlTag_object_handlers;
void php_wxHtmlTag_destruction_handler(zend_resource*);

class wxHtmlTag_php: public wxHtmlTag{
    public:

    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlTag{
    wxHtmlTag_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlTag;

void php_wxHtmlTag_free(zend_object *object);
zend_object* php_wxHtmlTag_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlTag_functions[] = {
    PHP_ME(php_wxHtmlTag, GetAllParams, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, GetName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, GetParam, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, GetParamAsColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, HasEnding, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, HasParam, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, ParseAsColour, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, ScanParam, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlTag, GetParamAsInt, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlTag * php_wxHtmlTag_fetch_object(zend_object *obj) {
    return (zo_wxHtmlTag *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlTag, zo)
    );
}

#define Z_wxHtmlTag_P(zv) \
    php_wxHtmlTag_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlWindow_entry;
extern zend_object_handlers wxphp_wxHtmlWindow_object_handlers;
void php_wxHtmlWindow_destruction_handler(zend_resource*);

class wxHtmlWindow_php: public wxHtmlWindow{
    public:

    wxHtmlWindow_php():wxHtmlWindow(){}
    wxHtmlWindow_php(wxWindow* parent, wxWindowID id=wxID_ANY, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxHW_DEFAULT_STYLE, const wxString& name="htmlWindow"):wxHtmlWindow(parent, id, pos, size, style, name){}
    
    bool OnCellClicked(wxHtmlCell* cell, wxCoord x, wxCoord y, const wxMouseEvent& event);
    void OnCellMouseHover(wxHtmlCell* cell, wxCoord x, wxCoord y);
    void OnLinkClicked(const wxHtmlLinkInfo& link);
    void OnSetTitle(const wxString& title);
    wxHtmlOpeningStatus OnOpeningURL(wxHtmlURLType type, const wxString& url, wxString* redirect) const;
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlWindow{
    wxHtmlWindow_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlWindow;

void php_wxHtmlWindow_free(zend_object *object);
zend_object* php_wxHtmlWindow_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlWindow_functions[] = {
    PHP_ME(php_wxObject, UnShare, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxObject, UnRef, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxObject, IsSameAs, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxObject, Ref, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxObject, GetClassInfo, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxObject, IsKindOf, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, Connect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, AddPendingEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, DeletePendingEvents, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, GetEvtHandlerEnabled, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, GetNextHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, GetPreviousHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, IsUnlinked, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, ProcessEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, ProcessEventLocally, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, ProcessPendingEvents, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, QueueEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, RemoveFilter, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, SafelyProcessEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, SetEvtHandlerEnabled, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxEvtHandler, Unlink, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Show, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, FindWindowById, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, FindWindow, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Enable, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Disable, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Close, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetSizer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetSizerAndFit, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetToolTip, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetWindowStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetWindowStyleFlag, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Update, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, UpdateWindowUI, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Validate, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, WarpPointer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, WindowToClientSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, UnsetToolTip, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, UnreserveControlId, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, TransferDataToWindow, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, TransferDataFromWindow, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ToggleWindowStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Thaw, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ShouldInheritColours, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetVirtualSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetValidator, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetTransparent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetSizeHints, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetScrollbar, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetScrollPos, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, AcceptsFocusFromKeyboard, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, AcceptsFocusRecursively, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, AddChild, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, AlwaysShowScrollbars, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, CacheBestSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, CanScroll, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, CanSetTransparent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, CaptureMouse, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Center, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, CenterOnParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Centre, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, CentreOnParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ClearBackground, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ClientToScreen, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ClientToWindowSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ConvertDialogToPixels, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ConvertPixelsToDialog, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, DragAcceptFiles, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, DoUpdateWindowUI, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, FindFocus, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, FindWindowByLabel, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, FindWindowByName, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Fit, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, FitInside, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Freeze, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetAutoLayout, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetBackgroundStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetBestSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetBestVirtualSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetBorder, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetCapture, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetCaret, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetCharHeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetCharWidth, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Destroy, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, DestroyChildren, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetClientAreaOrigin, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetClientRect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetClientSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetContainingSizer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetCursor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetEffectiveMinSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetEventHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetExtraStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetForegroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetGrandParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetHandle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetHelpText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetHelpTextAtPoint, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetId, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetLabel, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMaxClientSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMaxHeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMaxSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMaxWidth, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMinClientSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMinHeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMinSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetMinWidth, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetNextSibling, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetPopupMenuSelectionFromUser, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetPosition, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetPrevSibling, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetRect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetScreenPosition, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetScreenRect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetScrollPos, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetScrollRange, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetScrollThumb, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetSizer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetTextExtent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetToolTip, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetToolTipText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetUpdateClientRect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetUpdateRegion, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetValidator, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetVirtualSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetWindowBorderSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetWindowStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetWindowStyleFlag, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetWindowVariant, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HandleAsNavigationKey, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HandleWindowEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HasCapture, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HasExtraStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HasFlag, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HasFocus, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HasMultiplePages, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HasScrollbar, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HasTransparentBackground, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Hide, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, HitTest, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, GetLayoutDirection, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, InheritAttributes, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, InformFirstDirection, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, InvalidateBestSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsBeingDeleted, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsDoubleBuffered, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsEnabled, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsExposed, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsFrozen, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsRetained, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsScrollbarAlwaysShown, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsShown, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsShownOnScreen, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsThisEnabled, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, IsTopLevel, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, LineDown, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, LineUp, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Lower, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Move, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, MoveAfterInTabOrder, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, MoveBeforeInTabOrder, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Navigate, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, NavigateIn, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, NewControlId, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, PageDown, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, PageUp, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, PopupMenu, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, PostSizeEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, PostSizeEventToParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ProcessWindowEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ProcessWindowEventLocally, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, PushEventHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Raise, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Refresh, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, RefreshRect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ReleaseMouse, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, RemoveChild, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, RemoveEventHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, Reparent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ScreenToClient, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ScrollLines, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, ScrollPages, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SendSizeEvent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SendSizeEventToParent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetAutoLayout, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetBackgroundStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetCanFocus, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetCaret, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetClientSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetConstraints, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetContainingSizer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetCursor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetDropTarget, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetEventHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetExtraStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetFocusFromKbd, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetForegroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetHelpText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetId, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetInitialSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetLabel, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetLayoutDirection, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetMaxClientSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetMaxSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetMinClientSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetMinSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetNextHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetOwnBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetOwnFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetOwnForegroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetPosition, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetPreviousHandler, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetThemeEnabled, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxWindow, SetWindowVariant, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxPanel, AcceptsFocus, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxPanel, Create, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxPanel, InitDialog, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxPanel, Layout, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxPanel, SetFocus, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxPanel, SetFocusIgnoringChildren, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, SetScrollRate, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, SetScrollbars, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, SetTargetRect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, SetTargetWindow, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, ShowScrollbars, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, StopAutoScrolling, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, SetScrollPageSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, SetScale, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, Scroll, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, SendAutoScrollEvents, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, PrepareDC, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, IsAutoScrolling, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetViewStart, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetTargetWindow, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetTargetRect, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetScrollPixelsPerUnit, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetScrollPageSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetScrollLines, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetScaleY, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, GetScaleX, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, EnableScrolling, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, DoPrepareDC, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, DisableKeyboardScrolling, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, CalcUnscrolledPosition, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, CalcScrolledPosition, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxScrolled, AdjustScrollbars, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, AppendToPage, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, GetOpenedAnchor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, GetOpenedPage, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, GetOpenedPageTitle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, GetRelatedFrame, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, HistoryBack, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, HistoryCanBack, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, HistoryCanForward, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, HistoryClear, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, HistoryForward, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, LoadPage, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, LoadFile, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SelectAll, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SelectLine, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SelectWord, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SelectionToText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SetBorders, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SetPage, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SetRelatedFrame, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SetRelatedStatusBar, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SetStandardFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, ToText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, WriteCustomization, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxHtmlWindow, GetInternalRepresentation, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, AddFilter, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWindow, SetFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlWindow * php_wxHtmlWindow_fetch_object(zend_object *obj) {
    return (zo_wxHtmlWindow *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlWindow, zo)
    );
}

#define Z_wxHtmlWindow_P(zv) \
    php_wxHtmlWindow_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlDCRenderer_entry;
extern zend_object_handlers wxphp_wxHtmlDCRenderer_object_handlers;
void php_wxHtmlDCRenderer_destruction_handler(zend_resource*);

class wxHtmlDCRenderer_php: public wxHtmlDCRenderer{
    public:

    wxHtmlDCRenderer_php():wxHtmlDCRenderer(){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlDCRenderer{
    wxHtmlDCRenderer_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlDCRenderer;

void php_wxHtmlDCRenderer_free(zend_object *object);
zend_object* php_wxHtmlDCRenderer_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlDCRenderer_functions[] = {
    PHP_ME(php_wxHtmlDCRenderer, GetTotalHeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlDCRenderer, GetTotalWidth, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlDCRenderer, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxHtmlDCRenderer, SetStandardFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlDCRenderer, SetSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlDCRenderer, SetHtmlText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlDCRenderer, SetFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlDCRenderer, SetDC, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlDCRenderer, Render, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlDCRenderer * php_wxHtmlDCRenderer_fetch_object(zend_object *obj) {
    return (zo_wxHtmlDCRenderer *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlDCRenderer, zo)
    );
}

#define Z_wxHtmlDCRenderer_P(zv) \
    php_wxHtmlDCRenderer_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlEasyPrinting_entry;
extern zend_object_handlers wxphp_wxHtmlEasyPrinting_object_handlers;
void php_wxHtmlEasyPrinting_destruction_handler(zend_resource*);

class wxHtmlEasyPrinting_php: public wxHtmlEasyPrinting{
    public:

    wxHtmlEasyPrinting_php(const wxString& name="Printing", wxWindow* parentWindow=NULL):wxHtmlEasyPrinting(name, parentWindow){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlEasyPrinting{
    wxHtmlEasyPrinting_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlEasyPrinting;

void php_wxHtmlEasyPrinting_free(zend_object *object);
zend_object* php_wxHtmlEasyPrinting_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlEasyPrinting_functions[] = {
    PHP_ME(php_wxHtmlEasyPrinting, GetName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, GetPageSetupData, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, GetParentWindow, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, GetPrintData, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, PageSetup, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, PreviewFile, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, PreviewText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, PrintFile, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, PrintText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, SetFooter, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, SetHeader, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxHtmlEasyPrinting, SetStandardFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, SetParentWindow, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, SetName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlEasyPrinting, SetFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlEasyPrinting * php_wxHtmlEasyPrinting_fetch_object(zend_object *obj) {
    return (zo_wxHtmlEasyPrinting *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlEasyPrinting, zo)
    );
}

#define Z_wxHtmlEasyPrinting_P(zv) \
    php_wxHtmlEasyPrinting_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlPrintout_entry;
extern zend_object_handlers wxphp_wxHtmlPrintout_object_handlers;
void php_wxHtmlPrintout_destruction_handler(zend_resource*);

class wxHtmlPrintout_php: public wxHtmlPrintout{
    public:

    wxHtmlPrintout_php(const wxString& title="Printout"):wxHtmlPrintout(title){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlPrintout{
    wxHtmlPrintout_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlPrintout;

void php_wxHtmlPrintout_free(zend_object *object);
zend_object* php_wxHtmlPrintout_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlPrintout_functions[] = {
    PHP_ME(php_wxHtmlPrintout, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxHtmlPrintout, SetMargins, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlPrintout, SetHtmlText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlPrintout, SetHtmlFile, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlPrintout, SetHeader, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlPrintout, SetFooter, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlPrintout, SetFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlPrintout, AddFilter, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlPrintout * php_wxHtmlPrintout_fetch_object(zend_object *obj) {
    return (zo_wxHtmlPrintout *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlPrintout, zo)
    );
}

#define Z_wxHtmlPrintout_P(zv) \
    php_wxHtmlPrintout_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlTagsModule_entry;
extern zend_object_handlers wxphp_wxHtmlTagsModule_object_handlers;
void php_wxHtmlTagsModule_destruction_handler(zend_resource*);

class wxHtmlTagsModule_php: public wxHtmlTagsModule{
    public:

    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlTagsModule{
    wxHtmlTagsModule_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlTagsModule;

void php_wxHtmlTagsModule_free(zend_object *object);
zend_object* php_wxHtmlTagsModule_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlTagsModule_functions[] = {
    PHP_ME(php_wxHtmlTagsModule, FillHandlersTable, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlTagsModule * php_wxHtmlTagsModule_fetch_object(zend_object *obj) {
    return (zo_wxHtmlTagsModule *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlTagsModule, zo)
    );
}

#define Z_wxHtmlTagsModule_P(zv) \
    php_wxHtmlTagsModule_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlWinTagHandler_entry;
extern zend_object_handlers wxphp_wxHtmlWinTagHandler_object_handlers;
void php_wxHtmlWinTagHandler_destruction_handler(zend_resource*);

class wxHtmlWinTagHandler_php: public wxHtmlWinTagHandler{
    public:

    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlWinTagHandler{
    wxHtmlWinTagHandler_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlWinTagHandler;

void php_wxHtmlWinTagHandler_free(zend_object *object);
zend_object* php_wxHtmlWinTagHandler_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlWinTagHandler_functions[] = {
    PHP_FE_END
};
#endif


static inline zo_wxHtmlWinTagHandler * php_wxHtmlWinTagHandler_fetch_object(zend_object *obj) {
    return (zo_wxHtmlWinTagHandler *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlWinTagHandler, zo)
    );
}

#define Z_wxHtmlWinTagHandler_P(zv) \
    php_wxHtmlWinTagHandler_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxHtmlWinParser_entry;
extern zend_object_handlers wxphp_wxHtmlWinParser_object_handlers;
void php_wxHtmlWinParser_destruction_handler(zend_resource*);

class wxHtmlWinParser_php: public wxHtmlWinParser{
    public:

    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxHtmlWinParser{
    wxHtmlWinParser_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxHtmlWinParser;

void php_wxHtmlWinParser_free(zend_object *object);
zend_object* php_wxHtmlWinParser_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxHtmlWinParser_functions[] = {
    PHP_ME(php_wxHtmlWinParser, AddModule, arginfo_null, ZEND_ACC_STATIC|ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, CloseContainer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, CreateCurrentFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetActualColor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetAlign, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetCharHeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetCharWidth, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetContainer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetDC, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetFontBold, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetFontFace, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetFontFixed, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetFontItalic, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetFontSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetFontUnderlined, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetLink, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, GetLinkColor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetActualColor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetAlign, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetContainer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetDC, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, OpenContainer, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetFontBold, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetFontFace, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetFontFixed, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetFontItalic, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetFontSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetFontUnderlined, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetFonts, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetLink, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxHtmlWinParser, SetLinkColor, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxHtmlWinParser * php_wxHtmlWinParser_fetch_object(zend_object *obj) {
    return (zo_wxHtmlWinParser *)(
        (char *)(obj) - XtOffsetOf(zo_wxHtmlWinParser, zo)
    );
}

#define Z_wxHtmlWinParser_P(zv) \
    php_wxHtmlWinParser_fetch_object(Z_OBJ_P(zv))
#endif //WXPHP_HTML_H_GUARD
