/*
 * @author Mário Soares
 * @contributors Jefferson González
 * @contributors René Vögeli / Rangee GmbH
 * 
 * @license 
 * This file is part of wxPHP check the LICENSE file for information.
 * 
 * @note
 * This file was auto-generated by the wxPHP source maker
*/

#ifndef WXPHP_RICHTEXT_H_GUARD
#define WXPHP_RICHTEXT_H_GUARD

#include "references.h"
#include "object_types.h"

ZEND_BEGIN_ARG_INFO_EX(wxphp_richtext_get_args, 0, 0, 1)
    ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

extern zend_class_entry* php_wxTextAttr_entry;
extern zend_object_handlers wxphp_wxTextAttr_object_handlers;
void php_wxTextAttr_destruction_handler(zend_resource*);

class wxTextAttr_php: public wxTextAttr{
    public:

    wxTextAttr_php():wxTextAttr(){}
    wxTextAttr_php(const wxColour& colText, const wxColour& colBack=wxNullColour, const wxFont& font=wxNullFont, wxTextAttrAlignment alignment=wxTEXT_ALIGNMENT_DEFAULT):wxTextAttr(colText, colBack, font, alignment){}
    wxTextAttr_php(const wxTextAttr& attr):wxTextAttr(attr){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxTextAttr{
    wxTextAttr_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxTextAttr;

void php_wxTextAttr_free(void *object);
zend_object* php_wxTextAttr_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
static zend_function_entry php_wxTextAttr_functions[] = {
    PHP_ME(php_wxTextAttr, __construct, arginfo_null, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxTextAttr, SetFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetURL, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetTextEffects, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetTextEffectFlags, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetTextColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetRightIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetParagraphStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetParagraphSpacingBefore, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetParagraphSpacingAfter, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetOutlineLevel, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetListStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetLineSpacing, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetLeftIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFontWeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFontUnderlined, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFontStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFontSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, Apply, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetAlignment, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetBulletFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetBulletName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetBulletNumber, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetBulletStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetBulletText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetCharacterStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFlags, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontAttributes, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontEncoding, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontFaceName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontFamily, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontUnderlined, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetFontWeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetLeftIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetLeftSubIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetLineSpacing, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetListStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetOutlineLevel, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetParagraphSpacingAfter, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetParagraphSpacingBefore, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetParagraphStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetRightIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetTextColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetTextEffectFlags, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetTextEffects, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, GetURL, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasAlignment, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasBulletName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasBulletNumber, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasBulletStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasBulletText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasCharacterStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFlag, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFontEncoding, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFontFaceName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFontFamily, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFontItalic, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFontSize, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFontUnderlined, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasFontWeight, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasLeftIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasLineSpacing, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasListStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasOutlineLevel, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasPageBreak, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasParagraphSpacingAfter, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasParagraphSpacingBefore, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasParagraphStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasRightIndent, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasTabs, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasTextColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasTextEffects, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, HasURL, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, IsCharacterStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, IsDefault, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, IsParagraphStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, Merge, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetAlignment, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetBackgroundColour, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetBulletFont, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetBulletName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetBulletNumber, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetBulletStyle, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetBulletText, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetCharacterStyleName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFlags, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFontEncoding, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFontFaceName, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetFontFamily, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxTextAttr, SetPageBreak, arginfo_null, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxTextAttr * php_wxTextAttr_fetch_object(zend_object *obj) {
    return (zo_wxTextAttr *)(
        (char *)(obj) - XtOffsetOf(zo_wxTextAttr, zo)
    );
}

#define Z_wxTextAttr_P(zv) \
    php_wxTextAttr_fetch_object(Z_OBJ_P(zv))
#endif //WXPHP_RICHTEXT_H_GUARD
